export { default as Onboarding } from "./Onboarding"
export { default as Home } from "./Home"
export { default as Profile } from "./Profile"
export { default as Login } from "./Login"
export { default as ProductDetail } from "./ProductDetail"